# Generated by Django 3.2.5 on 2022-02-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_salesperson_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='salesperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson', to='rate.salesperson'),
        ),
    ]
