# Generated by Django 3.2.5 on 2022-02-13 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_auto_20220207_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
