# Generated by Django 3.2.5 on 2022-02-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_auto_20220213_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='image',
        ),
    ]
